baseURL = 'https://marsh.post-self.ink/'
languageCode = 'en-us'
title = 'Marsh'
theme = 'maddybook'
paginatePath = ""
disablePathToLower = true

[pagination]
    path = ""

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Rye Progress'
    home = 'https://makyo.ink'
    copyright = '2023'
    subtitle = 'Stories of Restoration'
    subtitleLink = 'https://post-self.ink'
    customCSS = ['/css/toledot.css']

[markup.goldmark.renderer]
    unsafe = true
